---
- name: IInstalling NTP
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on centos"
      yum:
        name: "{{item}}"
        state: present 
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - tree
        - unzip


    - name: Install NTP on Ubuntu
      apt:
        name: "{{item}}" 
        state: present
        update_Cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - tree
        - unzip

    - name: Start and Enable NTP on centos
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start and Enabled on Ubuntu
      service:
        name: ntp
        state: started 
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Add group
      group:
        name: devops
        state: present
    - name: Add user
      user:
        name: "{{item}}"
        state: present 
        groups: devops
      loop:
        - devops
        - kubernetes
        - jenkins



