---
- name: IInstalling NTP
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on centos"
      yum:
        name: ntp 
        state: present 
      when: ansible_distribution == "CentOs"
    - name: Install NTP on Ubuntu
      yum:
        name: ntp 
        state: present 
      when: ansible_distribution == "Ubuntu"