---
- name: copy files
  hosts: web1
  become: yes
  tasks:
    - name: copy files
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: ansible
        group: ansible
        mode: 0644
        backup : yes
