---
- name: Web-server
  hosts: web1
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
        name: "{{package}}"
        state: present 
    - name: start & Enable Httpd
      service:
        name: httpd
        state: started
        enabled: yes
  