---
- name: Web-server
  hosts: web1
  become: yes
  tasks:
    - debug:
        var: maria_db
        var: db_name
    - debug:
        msg: "value of {{"db_name"}}"
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present 
    - name: start & Enable Httpd
      service:
        name: httpd
        state: started
        enabled: yes

- name: Db-server
  hosts: db
  become: yes
  tasks:
    - name: Install MySql Db-server
      yum:
        name: "{{mariadb_server}}"
        state: present 
    - name: Start & Enable mariadb service
      service:
        name: "{{maria_db}}"
        state: started
        enabled: yes
    - name : Install Python packages
      yum:
        name: "{{mysql_python}}"
        state: present
    - name : Create Database "accounts"
      mysql_db:
        name: "{{db_name}}"
        state: present
    - name: create db user "admin"
      mysql_user:
        name: admin
        password: admin123
        priv: '*.*:ALL'
        state: present

