---
- hosts: nginx
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      file:
       path: /app/core
       state: directory
       mode: '0755'

    - name: Create the folder inside /app/core directory
      file:
        path: /app/core/nginxweb/lib/nginx
        state: directory
        mode: '0755'
    - name: extract tar.gz file
      unarchive:  
       src: /home/ansible/dum/nginx-1.14.2.tar.gz
       dest: /app/core/  
       remote_src: yes
    - name : copy .sh file from local to remote
      copy:
        src: /home/ansible/dum/nginx-conf.sh
        dest: /app/core/nginx-1.14.2   
        remote_src: yes   
    - name: Go to the folder and execute command
      command: chdir=/app/core/nginx-1.14.2      